import { Router } from "express";
import userRouter from "./user/index.js";
import postRouter from "./post/index.js";
import commentRouter from "./comment/index.js";
import followerRouter from "./follower/index.js";
import authenticateRouter from "./authentication/index.js";
const allRouter = Router();
allRouter.use(userRouter);
allRouter.use(postRouter);
allRouter.use(commentRouter);
allRouter.use(followerRouter);
allRouter.use(authenticateRouter);
export default allRouter;
